### ISSUE TITLE
ground speed calculation error

### ISSUE THREAD

**Issue by handleyw** [UgCS/sagetech-ardu#1]
There is a typo in line 146:
gps_message.speed_over_ground =sqrt((long)msg.vx * (long)msg.vx + (long)msg.vy * (long)msg.vx);

should be updated to:
gps_message.speed_over_ground =sqrt((long)msg.vx * (long)msg.vx + (long)msg.vy * (long)msg.vy);

**Comment by jdzerve** [comment]
Thanks for pointing this out. Fixed.
